export const UI_TEXT = {
  en: {
    goodMorning: "Good morning",
    goodEvening: "Good evening",
    goodNight: "Good night",
    todayCommand: "Today Command",
    bodyStatus: "Body Status",
    atlasScore: "Atlas Score",
    monthCalendar: "Month Calendar",
    prTracker: "PR Tracker",
    fatigueDeload: "Fatigue / Deload",
    myGoals: "My Goals",
    progressMemory: "Progress Memory",
    streakBadges: "Streak / Badges",
    progressPhotos: "Progress Photos",
    weeklyMetrics: "Weekly Metrics",
    weekPlan: "Week Plan",
    settings: "Settings",
    reminders: "Reminders",
    pages: "Pages",
    profileName: "Profile name",
    language: "Language",
    theme: "Theme",
    lightStarts: "Auto: light mode until 1:00 PM, dark mode from 1:00 PM to 11:59 PM.",
    openFullPhotos: "Open photo page",
    noPhotos: "No progress photos yet.",
    modeSuffix: "MODE",
    today: "TODAY",
    weeklyProgressIs: "Weekly progress is at",
    keepMoving: "Keep the protocol moving.",
    startToday: "START TODAY",
    edit: "Edit",
    save: "Save",
    set: "Set",
    backup: "Backup",
    resetWeek: "Reset Week",
    start: "START",
    target: "TARGET",
    change: "CHANGE",
    toGoal: "TO GOAL",
    protocolStable: "Protocol status stable",
    deloadActive: "Deload warning active",
    avgRpe: "Avg RPE",
    streak: "Streak",
    noPrsYet: "No PRs marked yet",
    markPrHint: "Use Notes > Mark as PR",
    averageRpe: "Average RPE:",
    noRpeNotes: "No RPE notes yet",
    deloadAdvice: "Consider lowering load, adding rest, or keeping sets submaximal.",
    noDeloadSignal: "No deload signal from current notes.",
    weeklyProtocol: "Weekly protocol",
    completedSessions: "Completed sessions",
    lastSaved: "Last saved",
    noProgressSaved: "No progress saved yet.",
    progressSavedMsg: "Progress saved.",
    savedTag: "SAVED",
    autoTag: "AUTO",
    exercisesWord: "exercises",
    weekStreak: "WEEK STREAK",
    daysClear: "DAYS CLEAR",
    weekOf: "WEEK OF",
    protocolStarted: "Protocol Started",
    twoWeekUpgrade: "2-WEEK UPGRADE",
    progressionLead: "Two weeks in. You can add +5 lb to all",
    progressionTail: "exercises, or keep your current weights. Nothing changes unless you pick one.",
    keepCurrent: "Keep current",
    applyFive: "Apply +5 lb",
    mWeekly: "WEEKLY",
    mDone: "DONE",
    mExercises: "EXERCISES",
    mSets: "SETS",
    mSessions: "SESSIONS",
    mCompleted: "COMPLETED",
    mCardio: "CARDIO",
    mDays: "DAYS",
    total: "TOTAL",
    latest: "LATEST",
    photoNote: "Photo note",
    choosePhoto: "Choose Photo",
    savePhoto: "Save Photo",
    noNote: "No note",
    calCompleted: "Completed",
    calTrained: "Trained",
    calMissed: "Missed",
    calRest: "Rest",
    calPlanned: "Planned",
    backHome: "Back Home",
    restTimer: "REST TIMER",
    recoverNext: "Recover, then attack the next set.",
    startAfterSet: "Start after a hard set.",
    restWord: "REST",
    readyWord: "READY",
    stopTimer: "Stop Timer",
    editDay: "Edit Day",
    quick: "Quick",
    full: "Full",
    doneWord: "done",
    setsWord: "sets",
    repsWord: "reps",
    leftWord: "left",
    cardioWarmup: "CARDIO / WARM-UP",
    recoveryMode: "RECOVERY MODE",
    restEatRebuild: "Rest. Eat. Rebuild.",
    quickSession: "QUICK SESSION",
    weightWord: "WEIGHT",
    leftCap: "LEFT",
    markExerciseDone: "Mark Exercise Done",
    notesWord: "Notes",
    fullSession: "Full Session",
    minusSet: "- Set",
    plusSet: "+ Set",
    totalSets: "TOTAL SETS",
    progressWord: "PROGRESS",
    atlasMenu: "ATLAS MENU",
    signedInAs: "Signed in as",
    workoutWord: "WORKOUT",
    manageWorkouts: "Manage Workouts",
    appWord: "APP",
    backupSync: "Backup / Sync",
    logout: "Logout",
    close: "Close",
    cancel: "Cancel",
    doneBtn: "Done",
    waterToday: "Water Today",
    waterTracking: "Water Tracking",
    glasses: "glasses",
    glassWord: "Glass",
    waterGoal: "Daily Goal",
    drinkReminder: "Stay hydrated. Aim for your daily goal.",
    coachTitle: "Coach",
    bodyTypeLabel: "Body Type Goal",
    tipsTitle: "Protocol Tips",
    bmiLabel: "BMI",
    bodyFatLabel: "Body Fat",
    leanMassLabel: "Lean Mass",
    ibwLabel: "Ideal Weight",
    sexLabel: "Sex",
    ageLabel: "Age",
    countdownTitle: "Countdown to Goal",
    finalStretch: "Final stretch!",
    almostThere: "Almost there. Don't stop!",
    daysLeft: "DAYS LEFT",
    maleLabel: "Male",
    femaleLabel: "Female",
    bodyComposition: "Body Composition",
    currentLabel: "CURRENT",
    heightLabel: "HEIGHT",
    editBodyStatus: "EDIT BODY STATUS",
    bodyTrend: "BODY TREND",
    stableSinceStart: "Stable since start",
    upFromStarting: "Up from starting weight",
    downFromStarting: "Down from starting weight",
    manualBodyCheck: "Manual body check",
    autoProgressCapture: "Auto progress capture",
    dayByDay: "DAY BY DAY",
    scoreBreakdown: "SCORE BREAKDOWN",
    weeklyCompletion: "Weekly completion",
    sessionTarget: "Session target",
    streakPressure: "Streak pressure",
    prMomentum: "PR momentum",
    streakLabel: "STREAK",
    prsLabel: "PRS",
    avgRpeLabel: "AVG RPE",
    deloadLabel: "DELOAD",
    exercisesLogged: "exercises logged",
    noEntrySaved: "No entry saved yet",
    totalPrs: "TOTAL PRS",
    heaviestLabel: "HEAVIEST",
    heaviestLoads: "HEAVIEST PROGRAMMED LOADS",
    highNotes: "HIGH NOTES",
    thisWeek: "THIS WEEK",
    lowerLoadAdvice: "Lower load, reduce intensity, or add recovery.",
    noFatigueWarning: "No fatigue warning from the current notes.",
    painSignalNote: "Pain marked Sharp/Stop or RPE 9-10 raises the warning signal.",
    recentSignals: "RECENT NOTE SIGNALS",
    deloadActiveVal: "ACTIVE",
    deloadClearVal: "CLEAR",
    noExerciseNotes: "No exercise notes yet",
    addPainRPE: "Add pain/RPE from any exercise",
    mainFocus: "MAIN FOCUS",
    targetDateSub: "Target date:",
    setMyGoals: "SET MY GOALS",
    remainingExercises: "REMAINING EXERCISES",
    setCompletionLabel: "SET COMPLETION",
    saveProgress: "SAVE PROGRESS",
    manualSave: "Manual save",
    autoSnapshot: "Auto snapshot",
    badgesLabel: "BADGES",
    photosLabel: "PHOTOS",
    albumsLabel: "ALBUMS",
    addPhotoLabel: "ADD PHOTO",
    dateField: "DATE",
    noteField: "NOTE",
    albumField: "ALBUM",
    noAlbum: "No album",
    newAlbumPlaceholder: "New album name",
    addPhotoBtn: "Add Photo",
    newAlbumBtn: "New Album",
    newAlbumTitle: "New Album",
    noAlbumsHint: "No albums yet. Create one to group your progress photos.",
    restTimerSub: "Default rest started automatically after every set.",
    createBtn: "Create",
    deleteAlbumBtn: "Delete album",
    noPhotosInAlbum: "No photos in this album yet.",
    setProgressLabel: "SET PROGRESS",
    manageWorkoutsSub: "Add, edit, or remove exercises and sessions.",
    addExerciseSection: "ADD EXERCISE",
    noExercisesYet: "No exercises in this session yet. Add one below.",
    exerciseLabel: "EXERCISE",
    removeBtn: "Remove",
    exerciseNamePlaceholder: "Exercise name",
    daySection: "DAY",
    sessionSection: "SESSION",
    sessionNameField: "SESSION NAME",
    timeField: "TIME",
    addSessionBtn: "Add Session",
    duplicateBtn: "Duplicate",
    deleteBtn: "Delete",
    sessionNamePlaceholder: "Session name",
    repsLabel: "REPS",
    customReminders: "CUSTOM REMINDERS",
    reminderTitlePlaceholder: "Reminder title",
    reminderMessagePlaceholder: "Reminder message",
    addReminderBtn: "ADD REMINDER",
    reminderOn: "On",
    reminderOff: "Off",
    editWeight: "EDIT WEIGHT",
    weekWord: "week",
    sessionsWord: "sessions",
    featDescToday: "The command center for the current day: start the session, jump into quick mode, and keep the week's protocol moving.",
    featDescBody: "Tracks current body weight against the starting point and target so the protocol has a visible physical direction.",
    featDescScore: "Combines weekly completion, sessions, streak, PRs, and fatigue into one performance signal.",
    featDescCalendar: "Shows the month as training status: completed, trained, missed, rest, or planned.",
    featDescPrs: "Collects every exercise marked as a PR from notes, then pairs it with the current programmed weight and date.",
    featDescFatigue: "Uses RPE and pain notes to show weekly strain and warn when the protocol may need a lighter day.",
    featDescGoals: "Keeps weekly targets and the main focus goal visible, with progress against each target.",
    featDescProgress: "Stores body-weight and weekly-performance snapshots so progress survives beyond today's checkboxes.",
    featDescBadges: "Turns consistency into simple streaks and badges without making the app feel noisy.",
    featDescPhotos: "Keeps local progress photos by date, weight, and note for visual comparison.",
    featDescMetrics: "Breaks down the full weekly workload: exercises, sets, sessions, cardio, completion, and set progress.",
    featDescWeek: "Shows the full seven-day split and gives fast access to every programmed workout day.",
    featDescNutrition: "Logs meals, calories and macros against a daily target built from your body data and goal.",
    featDescCardio: "Tracks standalone cardio sessions with distance, pace and estimated calories burned.",
    featDescChallenges: "Personal challenges tracked locally from your training, hydration and cardio logs.",
    unitSystem: "Units",
    metric: "Metric (kg, cm)",
    imperial: "Imperial (lb, in)",
    unitSystemSub: "Switches how weight, height and distance are shown. Stored data is not changed.",
    nutrition: "Nutrition",
    nutritionToday: "Nutrition Today",
    calories: "Calories",
    caloriesLabel: "CALORIES",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    addFood: "Add Food",
    customFood: "Custom Food",
    recentFoods: "Recent",
    calorieTarget: "Calorie Target",
    dailyTarget: "Daily Target",
    serving: "Serving",
    quantity: "Qty",
    bmrLabel: "BMR",
    tdeeLabel: "TDEE",
    macroSplit: "Macro Targets",
    caloriesLeft: "left",
    caloriesOver: "over",
    searchFood: "Search foods",
    activityLevel: "Activity Level",
    activitySedentary: "Sedentary",
    activityLight: "Lightly active",
    activityModerate: "Moderately active",
    activityActive: "Very active",
    activityAthlete: "Athlete",
    noFoodToday: "No food logged today.",
    foodName: "Food name",
    saveFood: "Save Food",
    nutritionHistory: "Recent Days",
    cardio: "Cardio",
    cardioType: "Activity",
    duration: "Duration",
    distance: "Distance",
    pace: "Pace",
    caloriesBurned: "Burned",
    addCardioSession: "Log Cardio",
    weeklyCardio: "This Week",
    cardioSessions: "Sessions",
    noCardioYet: "No cardio logged yet.",
    minutesShort: "min",
    cardioHistory: "Cardio History",
    measurements: "Measurements",
    neck: "Neck",
    chest: "Chest",
    waist: "Waist",
    hips: "Hips",
    arms: "Arms",
    thighs: "Thighs",
    calves: "Calves",
    addMeasurement: "Log Measurements",
    navyBodyFat: "Body Fat (Navy)",
    measurementHistory: "Measurement History",
    noMeasurements: "No measurements logged yet.",
    latestMeasure: "Latest",
    estimatedOneRM: "Est. 1RM",
    newPR: "NEW PERSONAL RECORD",
    volumeTrends: "Volume Trends",
    muscleBalance: "Muscle Group Balance",
    formCues: "Form Cues",
    personalBest: "Best",
    totalVolume: "Weekly Volume",
    viewCues: "Form cues",
    share: "Share",
    shareProgress: "Share Progress",
    shareCard: "Share Image",
    shareCopied: "Summary copied to clipboard.",
    challenges: "Challenges",
    newChallenge: "New Challenge",
    challengeTarget: "Target",
    challengeMetric: "Track",
    challengeWorkouts: "Workout days",
    challengeWater: "Water goal days",
    challengeCardio: "Cardio sessions",
    createChallenge: "Create Challenge",
    activeChallenges: "Active Challenges",
    noChallenges: "No challenges yet. Set one to stay accountable.",
    challengeDays: "Days",
    challengeDone: "Challenge complete!",
    challengeTitle: "Challenge name",
    beforeAfter: "Before / After",
    photoBefore: "Before",
    photoAfter: "After",
    dragToCompare: "Drag the slider to compare",
    comparePhotos: "Compare Photos",
    photoPrev: "Previous",
    photoNext: "Next",
    addFirstPhoto: "Tap to add your first progress photo",
    photoCount: "photos",
  },
  es: {
    goodMorning: "Buenos días",
    goodEvening: "Buenas tardes",
    goodNight: "Buenas noches",
    todayCommand: "Comando de Hoy",
    bodyStatus: "Estado Corporal",
    atlasScore: "Puntaje Atlas",
    monthCalendar: "Calendario Mensual",
    prTracker: "Récords Personales",
    fatigueDeload: "Fatiga / Descarga",
    myGoals: "Mis Metas",
    progressMemory: "Memoria de Progreso",
    streakBadges: "Racha / Insignias",
    progressPhotos: "Fotos de Progreso",
    weeklyMetrics: "Métricas Semanales",
    weekPlan: "Plan Semanal",
    settings: "Configuración",
    reminders: "Recordatorios",
    pages: "Páginas",
    profileName: "Nombre del perfil",
    language: "Idioma",
    theme: "Tema",
    lightStarts: "Auto: modo claro hasta la 1:00 PM, modo oscuro de 1:00 PM a 11:59 PM.",
    openFullPhotos: "Abrir página de fotos",
    noPhotos: "Aún no hay fotos de progreso.",
    modeSuffix: "",
    today: "HOY",
    weeklyProgressIs: "El progreso semanal está en",
    keepMoving: "Sigue con el protocolo.",
    startToday: "EMPEZAR HOY",
    edit: "Editar",
    save: "Guardar",
    set: "Definir",
    backup: "Respaldo",
    resetWeek: "Reiniciar Semana",
    start: "INICIO",
    target: "META",
    change: "CAMBIO",
    toGoal: "A LA META",
    protocolStable: "Protocolo estable",
    deloadActive: "Aviso de descarga activo",
    avgRpe: "RPE prom.",
    streak: "Racha",
    noPrsYet: "Aún no hay récords marcados",
    markPrHint: "Usa Notas > Marcar récord",
    averageRpe: "RPE promedio:",
    noRpeNotes: "Aún no hay notas de RPE",
    deloadAdvice: "Considera bajar la carga, descansar más o dejar las series submáximas.",
    noDeloadSignal: "Sin señal de descarga en las notas actuales.",
    weeklyProtocol: "Protocolo semanal",
    completedSessions: "Sesiones completadas",
    lastSaved: "Último guardado",
    noProgressSaved: "Aún no hay progreso guardado.",
    progressSavedMsg: "Progreso guardado.",
    savedTag: "GUARDADO",
    autoTag: "AUTO",
    exercisesWord: "ejercicios",
    weekStreak: "RACHA SEM.",
    daysClear: "DÍAS LIMPIOS",
    weekOf: "SEMANA DE",
    protocolStarted: "Protocolo Iniciado",
    twoWeekUpgrade: "MEJORA QUINCENAL",
    progressionLead: "Ya van dos semanas. Puedes sumar +5 lb a los",
    progressionTail: "ejercicios, o mantener tus pesos actuales. Nada cambia hasta que elijas.",
    keepCurrent: "Mantener actual",
    applyFive: "Aplicar +5 lb",
    mWeekly: "SEMANAL",
    mDone: "HECHO",
    mExercises: "EJERCICIOS",
    mSets: "SERIES",
    mSessions: "SESIONES",
    mCompleted: "COMPLETADAS",
    mCardio: "CARDIO",
    mDays: "DÍAS",
    total: "TOTAL",
    latest: "ÚLTIMA",
    photoNote: "Nota de la foto",
    choosePhoto: "Elegir foto",
    savePhoto: "Guardar foto",
    noNote: "Sin nota",
    calCompleted: "Completado",
    calTrained: "Entrenado",
    calMissed: "Perdido",
    calRest: "Descanso",
    calPlanned: "Planeado",
    backHome: "Volver al inicio",
    restTimer: "TEMPORIZADOR",
    recoverNext: "Recupérate y ataca la siguiente serie.",
    startAfterSet: "Inícialo tras una serie dura.",
    restWord: "DESC.",
    readyWord: "LISTO",
    stopTimer: "Detener",
    editDay: "Editar día",
    quick: "Rápido",
    full: "Completo",
    doneWord: "hechas",
    setsWord: "series",
    repsWord: "reps",
    leftWord: "restan",
    cardioWarmup: "CARDIO / CALENTAMIENTO",
    recoveryMode: "MODO RECUPERACIÓN",
    restEatRebuild: "Descansa. Come. Reconstruye.",
    quickSession: "SESIÓN RÁPIDA",
    weightWord: "PESO",
    leftCap: "RESTAN",
    markExerciseDone: "Marcar ejercicio hecho",
    notesWord: "Notas",
    fullSession: "Sesión completa",
    minusSet: "- Serie",
    plusSet: "+ Serie",
    totalSets: "SERIES TOTALES",
    progressWord: "PROGRESO",
    atlasMenu: "MENÚ ATLAS",
    signedInAs: "Sesión de",
    workoutWord: "ENTRENO",
    manageWorkouts: "Gestionar rutinas",
    appWord: "APP",
    backupSync: "Respaldo / Sync",
    logout: "Cerrar sesión",
    close: "Cerrar",
    cancel: "Cancelar",
    doneBtn: "Listo",
    waterToday: "Agua Hoy",
    waterTracking: "Control de Agua",
    glasses: "vasos",
    glassWord: "Vaso",
    waterGoal: "Meta Diaria",
    drinkReminder: "Mantente hidratado. Llega a tu meta diaria.",
    coachTitle: "Coach",
    bodyTypeLabel: "Meta de Cuerpo",
    tipsTitle: "Consejos del Protocolo",
    bmiLabel: "IMC",
    bodyFatLabel: "Grasa Corporal",
    leanMassLabel: "Masa Magra",
    ibwLabel: "Peso Ideal",
    sexLabel: "Sexo",
    ageLabel: "Edad",
    countdownTitle: "Cuenta Regresiva",
    finalStretch: "¡La recta final!",
    almostThere: "¡Casi ahí! No pares.",
    daysLeft: "DÍAS RESTANTES",
    maleLabel: "Hombre",
    femaleLabel: "Mujer",
    bodyComposition: "Composición Corporal",
    currentLabel: "ACTUAL",
    heightLabel: "ALTURA",
    editBodyStatus: "EDITAR ESTADO CORPORAL",
    bodyTrend: "TENDENCIA CORPORAL",
    stableSinceStart: "Estable desde el inicio",
    upFromStarting: "Subiendo desde el peso inicial",
    downFromStarting: "Bajando desde el peso inicial",
    manualBodyCheck: "Revisión corporal manual",
    autoProgressCapture: "Captura automática de progreso",
    dayByDay: "DÍA A DÍA",
    scoreBreakdown: "DESGLOSE DEL PUNTAJE",
    weeklyCompletion: "Cumplimiento semanal",
    sessionTarget: "Meta de sesiones",
    streakPressure: "Presión de racha",
    prMomentum: "Impulso de récords",
    streakLabel: "RACHA",
    prsLabel: "RÉCORDS",
    avgRpeLabel: "RPE PROM.",
    deloadLabel: "DESCARGA",
    exercisesLogged: "ejercicios registrados",
    noEntrySaved: "Aún no hay entrada guardada",
    totalPrs: "RÉCORDS TOTALES",
    heaviestLabel: "MÁS PESADO",
    heaviestLoads: "CARGAS PROGRAMADAS MÁS PESADAS",
    highNotes: "NOTAS ALTAS",
    thisWeek: "ESTA SEMANA",
    lowerLoadAdvice: "Baja la carga, reduce la intensidad o agrega recuperación.",
    noFatigueWarning: "Sin alerta de fatiga en las notas actuales.",
    painSignalNote: "Dolor Agudo/Parar o RPE 9-10 activa la señal de alerta.",
    recentSignals: "SEÑALES RECIENTES",
    deloadActiveVal: "ACTIVO",
    deloadClearVal: "DESPEJADO",
    noExerciseNotes: "Aún no hay notas de ejercicios",
    addPainRPE: "Agrega dolor/RPE en cualquier ejercicio",
    mainFocus: "ENFOQUE PRINCIPAL",
    targetDateSub: "Fecha meta:",
    setMyGoals: "DEFINIR MIS METAS",
    remainingExercises: "EJERCICIOS RESTANTES",
    setCompletionLabel: "SERIES COMPLETADAS",
    saveProgress: "GUARDAR PROGRESO",
    manualSave: "Guardado manual",
    autoSnapshot: "Captura automática",
    badgesLabel: "INSIGNIAS",
    photosLabel: "FOTOS",
    albumsLabel: "ÁLBUMES",
    addPhotoLabel: "AGREGAR FOTO",
    dateField: "FECHA",
    noteField: "NOTA",
    albumField: "ÁLBUM",
    noAlbum: "Sin álbum",
    newAlbumPlaceholder: "Nombre del álbum",
    addPhotoBtn: "Agregar Foto",
    newAlbumBtn: "Nuevo Álbum",
    newAlbumTitle: "Nuevo Álbum",
    noAlbumsHint: "Aún no tienes álbumes. Crea uno para agrupar tus fotos de progreso.",
    restTimerSub: "Descanso por defecto que inicia automáticamente tras cada serie.",
    createBtn: "Crear",
    deleteAlbumBtn: "Eliminar álbum",
    noPhotosInAlbum: "Aún no hay fotos en este álbum.",
    setProgressLabel: "PROGRESO DE SERIES",
    manageWorkoutsSub: "Agrega, edita o elimina ejercicios y sesiones.",
    addExerciseSection: "AGREGAR EJERCICIO",
    noExercisesYet: "Aún no hay ejercicios en esta sesión. Agrega uno abajo.",
    exerciseLabel: "EJERCICIO",
    removeBtn: "Eliminar",
    exerciseNamePlaceholder: "Nombre del ejercicio",
    daySection: "DÍA",
    sessionSection: "SESIÓN",
    sessionNameField: "NOMBRE DE SESIÓN",
    timeField: "HORA",
    addSessionBtn: "Agregar Sesión",
    duplicateBtn: "Duplicar",
    deleteBtn: "Eliminar",
    sessionNamePlaceholder: "Nombre de la sesión",
    repsLabel: "REPS",
    customReminders: "RECORDATORIOS PERSONALIZADOS",
    reminderTitlePlaceholder: "Título del recordatorio",
    reminderMessagePlaceholder: "Mensaje del recordatorio",
    addReminderBtn: "AGREGAR RECORDATORIO",
    reminderOn: "Activo",
    reminderOff: "Inactivo",
    editWeight: "EDITAR PESO",
    weekWord: "semana",
    sessionsWord: "sesiones",
    featDescToday: "El centro de mando del día actual: inicia la sesión, entra al modo rápido y mantén el protocolo semanal en movimiento.",
    featDescBody: "Rastrea el peso corporal actual contra el punto de inicio y la meta para que el protocolo tenga una dirección física visible.",
    featDescScore: "Combina cumplimiento semanal, sesiones, racha, récords y fatiga en una sola señal de rendimiento.",
    featDescCalendar: "Muestra el mes como estado de entrenamiento: completado, entrenado, perdido, descanso o planeado.",
    featDescPrs: "Reúne cada ejercicio marcado como récord en las notas y lo empareja con el peso programado actual y la fecha.",
    featDescFatigue: "Usa notas de RPE y dolor para mostrar la carga semanal y avisar cuando el protocolo puede necesitar un día más ligero.",
    featDescGoals: "Mantiene visibles las metas semanales y el objetivo principal, con progreso hacia cada meta.",
    featDescProgress: "Guarda instantáneas de peso corporal y rendimiento semanal para que el progreso sobreviva más allá de los checkboxes de hoy.",
    featDescBadges: "Convierte la constancia en rachas e insignias simples sin hacer la app ruidosa.",
    featDescPhotos: "Guarda fotos de progreso locales por fecha, peso y nota para comparación visual.",
    featDescMetrics: "Desglosa la carga semanal completa: ejercicios, series, sesiones, cardio, completados y progreso de series.",
    featDescWeek: "Muestra la división completa de siete días y da acceso rápido a cada día de entrenamiento programado.",
    featDescNutrition: "Registra comidas, calorías y macros contra una meta diaria calculada con tus datos y tu objetivo.",
    featDescCardio: "Registra sesiones de cardio con distancia, ritmo y calorías estimadas quemadas.",
    featDescChallenges: "Retos personales calculados localmente desde tu entrenamiento, hidratación y cardio.",
    unitSystem: "Unidades",
    metric: "Métrico (kg, cm)",
    imperial: "Imperial (lb, in)",
    unitSystemSub: "Cambia cómo se muestran peso, altura y distancia. Los datos guardados no cambian.",
    nutrition: "Nutrición",
    nutritionToday: "Nutrición Hoy",
    calories: "Calorías",
    caloriesLabel: "CALORÍAS",
    protein: "Proteína",
    carbs: "Carbohidratos",
    fat: "Grasa",
    breakfast: "Desayuno",
    lunch: "Almuerzo",
    dinner: "Cena",
    snack: "Snack",
    addFood: "Agregar Alimento",
    customFood: "Alimento Personalizado",
    recentFoods: "Recientes",
    calorieTarget: "Meta de Calorías",
    dailyTarget: "Meta Diaria",
    serving: "Porción",
    quantity: "Cant.",
    bmrLabel: "TMB",
    tdeeLabel: "GET",
    macroSplit: "Metas de Macros",
    caloriesLeft: "restantes",
    caloriesOver: "de más",
    searchFood: "Buscar alimentos",
    activityLevel: "Nivel de Actividad",
    activitySedentary: "Sedentario",
    activityLight: "Poco activo",
    activityModerate: "Moderadamente activo",
    activityActive: "Muy activo",
    activityAthlete: "Atleta",
    noFoodToday: "No has registrado comida hoy.",
    foodName: "Nombre del alimento",
    saveFood: "Guardar Alimento",
    nutritionHistory: "Días Recientes",
    cardio: "Cardio",
    cardioType: "Actividad",
    duration: "Duración",
    distance: "Distancia",
    pace: "Ritmo",
    caloriesBurned: "Quemadas",
    addCardioSession: "Registrar Cardio",
    weeklyCardio: "Esta Semana",
    cardioSessions: "Sesiones",
    noCardioYet: "Aún no hay cardio registrado.",
    minutesShort: "min",
    cardioHistory: "Historial de Cardio",
    measurements: "Medidas",
    neck: "Cuello",
    chest: "Pecho",
    waist: "Cintura",
    hips: "Cadera",
    arms: "Brazos",
    thighs: "Muslos",
    calves: "Pantorrillas",
    addMeasurement: "Registrar Medidas",
    navyBodyFat: "Grasa Corporal (Navy)",
    measurementHistory: "Historial de Medidas",
    noMeasurements: "Aún no hay medidas registradas.",
    latestMeasure: "Última",
    estimatedOneRM: "1RM Est.",
    newPR: "NUEVO RÉCORD PERSONAL",
    volumeTrends: "Tendencia de Volumen",
    muscleBalance: "Balance por Grupo Muscular",
    formCues: "Indicaciones de Técnica",
    personalBest: "Mejor",
    totalVolume: "Volumen Semanal",
    viewCues: "Técnica",
    share: "Compartir",
    shareProgress: "Compartir Progreso",
    shareCard: "Compartir Imagen",
    shareCopied: "Resumen copiado al portapapeles.",
    challenges: "Retos",
    newChallenge: "Nuevo Reto",
    challengeTarget: "Meta",
    challengeMetric: "Medir",
    challengeWorkouts: "Días de entreno",
    challengeWater: "Días de meta de agua",
    challengeCardio: "Sesiones de cardio",
    createChallenge: "Crear Reto",
    activeChallenges: "Retos Activos",
    noChallenges: "Aún no hay retos. Crea uno para mantener el compromiso.",
    challengeDays: "Días",
    challengeDone: "¡Reto completado!",
    challengeTitle: "Nombre del reto",
    beforeAfter: "Antes / Después",
    photoBefore: "Antes",
    photoAfter: "Después",
    dragToCompare: "Desliza para comparar",
    comparePhotos: "Comparar Fotos",
    photoPrev: "Anterior",
    photoNext: "Siguiente",
    addFirstPhoto: "Toca para agregar tu primera foto de progreso",
    photoCount: "fotos",
  },
};
